In [1]:
import sys
sys.path.append('..')

import numpy as np
import torch
from torch import nn
from torch.autograd import Variable
from torchvision.datasets import CIFAR10

In [ ]:
def conv_block(in_channel, out_channel):
    layer = nn.Sequential(
        nn.BatchNorm2d(in_channel),
        nn.ReLU(True),
        nn.Conv2d(in_channel, out_channel, 3, padding=1, bias=False)
    )
    return layer

In [47]:
# from utils import train

def data_tf(x):
    x = x.resize((96, 96), 2) # 将图片放大到 96 x 96
    x = np.array(x, dtype='float32') / 255
    x = (x - 0.5) / 0.5 # 标准化，这个技巧之后会讲到
    x = x.transpose((2, 0, 1)) # 将 channel 放到第一维，只是 pytorch 要求的输入方式
    x = torch.from_numpy(x)
    return x
     
train_set = CIFAR10('./data', train=True, transform=data_tf, download=True)
train_data = torch.utils.data.DataLoader(train_set, batch_size=64, shuffle=True)
test_set = CIFAR10('./data', train=False, transform=data_tf, download=True)
test_data = torch.utils.data.DataLoader(test_set, batch_size=128, shuffle=False)

100%|█████████████████████████| 170498071/170498071 [06:26<00:00, 441663.26it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified


In [51]:
for im, label in train_data:
    break

In [55]:
im.shape
## 一份batch总共有64张图片，每张图片的形状都是3x96x96. torch要求维度要放在第一维。
## x.transpose是啥意思呢，就是维度置换，把比如第x维改到第y维去，这种。

torch.Size([64, 3, 96, 96])

In [56]:
nn.BatchNorm2d(3)(im)

tensor([[[[ 1.3471e+00,  1.3471e+00,  1.3299e+00,  ...,  1.3643e+00,
            1.3471e+00,  1.3471e+00],
          [ 1.3471e+00,  1.3471e+00,  1.3299e+00,  ...,  1.3643e+00,
            1.3471e+00,  1.3471e+00],
          [ 1.3471e+00,  1.3471e+00,  1.3299e+00,  ...,  1.3471e+00,
            1.3299e+00,  1.3299e+00],
          ...,
          [ 9.3359e-01,  9.3359e-01,  8.9913e-01,  ...,  1.7548e-01,
            1.5825e-01,  1.5825e-01],
          [ 9.1636e-01,  9.1636e-01,  8.9913e-01,  ..., -6.5734e-02,
           -8.2964e-02, -8.2964e-02],
          [ 9.1636e-01,  9.1636e-01,  8.9913e-01,  ..., -6.5734e-02,
           -8.2964e-02, -8.2964e-02]],

         [[ 1.1639e+00,  1.1639e+00,  1.1464e+00,  ...,  1.1989e+00,
            1.1989e+00,  1.1989e+00],
          [ 1.1639e+00,  1.1639e+00,  1.1464e+00,  ...,  1.1989e+00,
            1.1989e+00,  1.1989e+00],
          [ 1.1639e+00,  1.1639e+00,  1.1464e+00,  ...,  1.1989e+00,
            1.1989e+00,  1.1989e+00],
          ...,
     

In [57]:
im

tensor([[[[ 0.5451,  0.5451,  0.5373,  ...,  0.5529,  0.5451,  0.5451],
          [ 0.5451,  0.5451,  0.5373,  ...,  0.5529,  0.5451,  0.5451],
          [ 0.5451,  0.5451,  0.5373,  ...,  0.5451,  0.5373,  0.5373],
          ...,
          [ 0.3569,  0.3569,  0.3412,  ...,  0.0118,  0.0039,  0.0039],
          [ 0.3490,  0.3490,  0.3412,  ..., -0.0980, -0.1059, -0.1059],
          [ 0.3490,  0.3490,  0.3412,  ..., -0.0980, -0.1059, -0.1059]],

         [[ 0.4353,  0.4353,  0.4275,  ...,  0.4510,  0.4510,  0.4510],
          [ 0.4353,  0.4353,  0.4275,  ...,  0.4510,  0.4510,  0.4510],
          [ 0.4353,  0.4353,  0.4275,  ...,  0.4510,  0.4510,  0.4510],
          ...,
          [ 0.4118,  0.4118,  0.3961,  ..., -0.1294, -0.1373, -0.1373],
          [ 0.4118,  0.4118,  0.3961,  ..., -0.2549, -0.2627, -0.2627],
          [ 0.4118,  0.4118,  0.3961,  ..., -0.2549, -0.2627, -0.2627]],

         [[ 0.3333,  0.3333,  0.3255,  ...,  0.4431,  0.4431,  0.4431],
          [ 0.3333,  0.3333,  

In [58]:
torch.mean(im, )

<function torch._VariableFunctionsClass.mean>

In [62]:
torch.cuda.is_available()

False

In [63]:
nn.Conv2d?

In [64]:
Variable?

In [68]:
im.device()

TypeError: 'torch.device' object is not callable

In [72]:
im.to(
    torch.device("mps")
)

tensor([[[[ 0.5451,  0.5451,  0.5373,  ...,  0.5529,  0.5451,  0.5451],
          [ 0.5451,  0.5451,  0.5373,  ...,  0.5529,  0.5451,  0.5451],
          [ 0.5451,  0.5451,  0.5373,  ...,  0.5451,  0.5373,  0.5373],
          ...,
          [ 0.3569,  0.3569,  0.3412,  ...,  0.0118,  0.0039,  0.0039],
          [ 0.3490,  0.3490,  0.3412,  ..., -0.0980, -0.1059, -0.1059],
          [ 0.3490,  0.3490,  0.3412,  ..., -0.0980, -0.1059, -0.1059]],

         [[ 0.4353,  0.4353,  0.4275,  ...,  0.4510,  0.4510,  0.4510],
          [ 0.4353,  0.4353,  0.4275,  ...,  0.4510,  0.4510,  0.4510],
          [ 0.4353,  0.4353,  0.4275,  ...,  0.4510,  0.4510,  0.4510],
          ...,
          [ 0.4118,  0.4118,  0.3961,  ..., -0.1294, -0.1373, -0.1373],
          [ 0.4118,  0.4118,  0.3961,  ..., -0.2549, -0.2627, -0.2627],
          [ 0.4118,  0.4118,  0.3961,  ..., -0.2549, -0.2627, -0.2627]],

         [[ 0.3333,  0.3333,  0.3255,  ...,  0.4431,  0.4431,  0.4431],
          [ 0.3333,  0.3333,  